export const Questions = [
  {
    id: 1,
    ques: 'Who was the Governor General Of Pakistan?',
    choice1: 'Allama Iqbal',
    choice2: 'Quaid-e-Azam',
    choice3: 'Benazir Bhutto',
    choice4: 'Chowdury Rehmat',
    ans: 'Quaid-e-Azam',
  },

  {
    id: 2,
    ques: 'Who is the Nation Poet Of Pakistan?',

    choice1: 'Allama Iqbal',
    choice2: 'Quaid-e-Azam',
    choice3: 'Mirza Galib',
    choice4: 'Chowdury Rehmat',
    ans: 'Allama Iqbal',
  },
  {
    id: 3,
    ques: 'The International Literacy Day is observed on?',
    choice1: 'Sep 8',
    choice2: 'Nov 28',
    choice3: 'May 2',
    choice4: 'Sep 22',
    ans: 'Sep 8',
  },
  {
    id: 4,
    ques: 'Bahubali festival is related to?',
    choice1: 'Islam',
    choice2: 'Hinduism',
    choice3: 'Buddhism',
    choice4: 'Jainism',
    ans: 'Jainism',
  },
  {
    id: 5,
    ques: 'Which day is observed as the World Standards Day?',
    choice1: 'June 26',
    choice2: 'Oct 14',
    choice3: 'Nov 15',
    choice4: 'Dec 2',
    ans: 'Oct 14',
  },
  {
    id: 6,
    ques: 'The working principle of a washing machine is',
    choice1: 'Reverse osmosis',
    choice2: 'Diffusion',
    choice3: 'Dialysis',
    choice4: 'Centrifugation',
    ans: 'Centrifugation',
  },

  {
    id: 7,
    ques: 'Who was the Governor General Of Pakistan?',

    choice1: 'Allama Iqbal',
    choice2: 'Quaid-e-Azam',
    choice3: 'Mirza Galib',
    choice4: 'Chowdury Rehmat',
    ans: 'Allama Iqbal',
  },
  {
    id: 8,
    ques: 'Urdu was declared national language of Pakistan in?',
    choice1: 'April 1950',
    choice2: 'April 1955',
    choice3: 'April 1954',
    choice4: 'April 1952',
    ans: 'April 1954',
  },
  {
    id: 9,
    ques: 'Bahubali festival is related to?',
    choice1: 'Islam',
    choice2: 'Hinduism',
    choice3: 'Buddhism',
    choice4: 'Jainism',
    ans: 'Jainism',
  },
  {
    id: 10,
    ques: 'Which day is observed as the World Standards Day?',
    choice1: 'June 26',
    choice2: 'Oct 14',
    choice3: 'Nov 15',
    choice4: 'Dec 2',
    ans: 'Oct 14',
  },
  {
    id: 11,
    ques: 'John’s mother had three children. The first child was named April. The second child was named May. What was the third child’s name??',
    choice1: 'June',
    choice2: 'Oct',
    choice3: 'Dec',
    choice4: 'John',
    ans: 'John',
  },
  {
    id: 12,
    ques: 'Before Mount Everest was discovered, which was the highest mountain in the world?',
    choice1: 'Mount Everest',
    choice2: 'K2',
    choice3: 'Nanga Parbat',
    choice4: 'Denali',
    ans: 'Oct 14',
  },{
    id: 13,
    ques: 'If you threw a red stone into a green sea, what would it come back as?',
    choice1: 'Red',
    choice2: 'Green',
    choice3: 'Transparent',
    choice4: 'Wet',
    ans: 'Wet',
  },{
    id: 14,
    ques: 'The first news paper in the world was started by ?',
    choice1: 'China',
    choice2: 'Japan',
    choice3: 'Usa',
    choice4: 'India',
    ans: 'China',
  },{
    id: 15,
    ques: 'Which is considered as oldest civilization of the world ?',
    choice1: 'Egyptain Civilization',
    choice2: 'Harappan Civilization',
    choice3: 'Mesopotamian Civilization',
    choice4: 'Chinese Civilization',
    ans: 'Mesopotamian Civilization',
  },{
    id: 16,
    ques: 'When did the first Railway Train begin to carry passengers and freight?',
    choice1: '1814 AD',
    choice2: '1878 AD',
    choice3: '1830 AD',
    choice4: '1853 AD',
    ans: '1830 AD',
  },{
    id: 17,
    ques: 'When did World War 2 start?',
    choice1: '1936',
    choice2: '1938',
    choice3: '1939',
    choice4: '1940',
    ans: '1939',
  },{
    id: 18,
    ques: 'In which year America got independence?',
    choice1: '1760',
    choice2: '1776',
    choice3: '1780',
    choice4: '1782',
    ans: '1976',
  },{
    id: 19,
    ques: 'Who said that " Man is a political animal?',
    choice1: 'Aristotle',
    choice2: 'Karl Marx',
    choice3: 'Plato',
    choice4: 'Lenin',
    ans: 'Aristotle',
  },{
    id: 20,
    ques: 'Who is known as "Father of History?',
    choice1: 'Mark Antnoy',
    choice2: 'Nero',
    choice3: 'Herodotus',
    choice4: 'Homer',
    ans: 'Herodotus',
  },{
    id: 12,
    ques: 'Before Mount Everest was discovered, which was the highest mountain in the world?',
    choice1: 'Mount Everest',
    choice2: 'K2',
    choice3: 'Nanga Parbat',
    choice4: 'Denali',
    ans: 'Oct 14',
  },
];

export const getQuestion = () => {
  let no = Math.floor(Math.random() * Math.floor(10));
  return Questions[no];
};
